In [2]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.Collecting pandas
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/87/03/fe50521919aa981f6a1c197037da4623a267b0e5f42246d69ba048e86da3/pandas-2.2.0-cp312-cp312-win_amd64.whl.metadata
  Downloading pandas-2.2.0-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy<2,>=1.26.0 (from pandas)
  Obtaining dependency information for numpy<2,>=1.26.0 from https://files.pythonhosted.org/packages/ad/11/52fbe97fd84c91105b651d25a122f8deed6d3519afb14f9771fac1c9b7de/numpy-1.26.3-cp312-cp312-win_amd64.whl.metadata
  Downloading numpy-1.26.3-cp312-cp312-win_amd64.whl.metadata (61 kB)
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------------------- ------------------ 30.7/61.2 kB 640.0 kB/s eta 0:00:01
     ---------------------------------------- 61.2/61.2 kB 1.1 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nigel.zannou\appdata\roaming\python\python312\site-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl.metadata
  Downloading pytz-2023.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Obtaining dependency information for tzdata>=2022.7 from https://files.pythonhosted.org/packages/a3/fb/52b62131e21b24ee297e4e95ed41eba29647dad0e0051a92bb66b43c70ff/tzdata-2023.4-py2.py3-none-any.whl.metadata
  Downloading tzdata-2023.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\nigel.zannou\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.0-cp312-cp312-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ----- ---------------------------------- 1.5/11.5 MB 45.4 MB/s eta 0:00:01
   ---------------- ----------------------- 4.7/11.5 MB 58.8 MB/s eta 0:00:01
   ---------------------------- ----------- 8.0/11.5 MB 64.3 MB/s eta 0:00:01
   ---------------------------------------  11.5/11.5 MB 73.1 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 54.7 MB/s eta 0:00:00
Downloading numpy-1.26.3-cp312-cp312-win_amd64.whl (15.5 MB)
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   -------- ------------------------------- 3.3/15.5 MB 69.1 MB/s eta 0:00:01
   ------------------- -------------------- 7.5/15.5 MB 79.7 MB/s eta 0:00:01
   ----------------------------- ---------- 11.4/15.5 MB 81.8 MB/s eta 0:00:01
   ---------------------------------------  15.2/15.5 MB 81.8 MB/s eta 0:00:01
   ---------------------------------------  15.5/15.5 MB 81.8 MB/s eta 0:00:01
   ---------------------------------------- 15.5/15.5 MB 54.7 MB/s eta 0:00:00
Downloading pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
   ---------------------------------------- 0.0/502.5 kB ? eta -:--:--
   --------------------------------------- 502.5/502.5 kB 30.8 MB/s eta 0:00:00
Downloading tzdata-2023.4-py2.py3-none-any.whl (346 kB)
   ---------------------------------------- 0.0/346.6 kB ? eta -:--:--
   --------------------------------------- 346.6/346.6 kB 10.8 MB/s eta 0:00:00
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-1.26.3 pandas-2.2.0 pytz-2023.3.post1 tzdata-2023.4

  WARNING: The script f2py.exe is installed in 'c:\Users\nigel.zannou\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [38]:
import pandas as pd

In [39]:
df_GDP_cleaning = pd.read_csv(r"C:\Users\nigel.zannou\Desktop\Projet\3_Data_cleaning_on_merged_dataset\merged_dataset_to_clean.csv",index_col=0)

In [40]:
df_GDP_cleaning.head()

,Country Name,Country Code,Year,Birth Rate,GDP per Capita,Population_male,Population_female,Population_total,15_to_19_women_rate,20_to_24_women_rate,25_to_29_women_rate,30_to_34_women_rate,35_to_39_women_rate,40_to_44_women_rate,Median_age,Human Development Index,PM2.5_pollution,Female_employment_rate,Urban population rate
0,Afghanistan,AFG,2000,49.664,NaN,9815442,9727541,19542982,9.898899,8.404560,7.022391,5.750703,4.654414,3.754875,14.1,0.335,51.554534,13.644,22.078
1,Angola,AGO,2000,47.647,556.884244,8054751,8339311,16394062,10.266795,8.441950,7.114652,6.260984,5.298651,4.237520,15.6,0.375,28.133895,73.050,50.087
2,Albania,ALB,2000,17.076,1126.683340,1531486,1557540,3089027,9.699775,7.940675,7.356948,7.266261,7.168376,6.665580,26.3,0.677,24.302869,40.674,41.741
3,Andorra,AND,2000,11.300,21620.465102,34285,31812,66097,5.158431,6.165912,8.702691,10.220986,10.131397,8.611530,36.6,0.818,13.618431,NaN,92.395
4,United Arab Emirates,ARE,2000,16.660,31855.500605,2237588,1037745,3275333,12.375337,11.914193,10.863694,9.614833,7.606297,5.701591,26.1,0.796,43.648344,32.672,80.236

# Remplacement des valeurs manquantes pour l'Afgahanistan pour 2000 et 2001

In [41]:

df_GDP_cleaning.loc[(df_GDP_cleaning['Country Name'] == 'Afghanistan') & (df_GDP_cleaning['Year'] == 2001), 'GDP per Capita'] = 125
df_GDP_cleaning.loc[(df_GDP_cleaning['Country Name'] == 'Afghanistan') & (df_GDP_cleaning['Year'] == 2000), 'GDP per Capita'] = 181
df_GDP_cleaning

,Country Name,Country Code,Year,Birth Rate,GDP per Capita,Population_male,Population_female,Population_total,15_to_19_women_rate,20_to_24_women_rate,25_to_29_women_rate,30_to_34_women_rate,35_to_39_women_rate,40_to_44_women_rate,Median_age,Human Development Index,PM2.5_pollution,Female_employment_rate,Urban population rate
0,Afghanistan,AFG,2000,49.664,181.000000,9815442,9727541,19542982,9.898899,8.404560,7.022391,5.750703,4.654414,3.754875,14.1,0.335,51.554534,13.644,22.078
1,Angola,AGO,2000,47.647,556.884244,8054751,8339311,16394062,10.266795,8.441950,7.114652,6.260984,5.298651,4.237520,15.6,0.375,28.133895,73.050,50.087
2,Albania,ALB,2000,17.076,1126.683340,1531486,1557540,3089027,9.699775,7.940675,7.356948,7.266261,7.168376,6.665580,26.3,0.677,24.302869,40.674,41.741
3,Andorra,AND,2000,11.300,21620.465102,34285,31812,66097,5.158431,6.165912,8.702691,10.220986,10.131397,8.611530,36.6,0.818,13.618431,NaN,92.395
4,United Arab Emirates,ARE,2000,16.660,31855.500605,2237588,1037745,3275333,12.375337,11.914193,10.863694,9.614833,7.606297,5.701591,26.1,0.796,43.648344,32.672,80.236
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3557,Vanuatu,VUT,2021,29.438,3044.573640,160506,158631,319137,9.363584,8.525788,8.643987,7.815962,6.216018,4.761064,19.5,0.607,NaN,59.035,25.665
3558,Samoa,WSM,2021,27.254,3857.689742,111550,107213,218764,9.481082,8.285337,7.811516,6.095781,5.310432,5.229752,20.6,0.707,NaN,34.883,17.742
3559,South Africa,ZAF,2021,19.821,7073.612754,28894608,30497646,59392255,7.590166,7.507733,8.707692,9.275422,8.003288,5.762863,27.1,0.713,NaN,34.612,67.847
3560,Zambia,ZMB,2021,34.511,1134.713454,9609004,9864121,19473125,10.995212,9.306389,7.991188,6.857783,5.784383,4.648448,16.9,0.565,NaN,50.605,45.192
3561,Zimbabwe,ZWE,2021,30.537,1773.920411,7543690,8449834,15993524,10.872244,9.649409,7.654251,7.000310,7.077696,5.205635,18.1,0.593,NaN,55.975,32.303

In [42]:
df_GDP_cleaning.loc[df_GDP_cleaning["Country Name"]=="Afghanistan"]

,Country Name,Country Code,Year,Birth Rate,GDP per Capita,Population_male,Population_female,Population_total,15_to_19_women_rate,20_to_24_women_rate,25_to_29_women_rate,30_to_34_women_rate,35_to_39_women_rate,40_to_44_women_rate,Median_age,Human Development Index,PM2.5_pollution,Female_employment_rate,Urban population rate
0,Afghanistan,AFG,2000,49.664,181.000000,9815442,9727541,19542982,9.898899,8.404560,7.022391,5.750703,4.654414,3.754875,14.1,0.335,51.554534,13.644,22.078
152,Afghanistan,AFG,2001,48.979,125.000000,9895467,9793166,19688632,9.903712,8.335022,6.997625,5.745941,4.653791,3.752311,14.1,0.337,NaN,13.758,22.169
304,Afghanistan,AFG,2002,48.201,182.174037,10562202,10438055,21000256,9.957368,8.265151,6.972022,5.741075,4.656548,3.752083,14.0,0.362,NaN,13.884,22.261
458,Afghanistan,AFG,2003,47.350,199.643228,11397483,11247647,22645130,10.044723,8.202636,6.945057,5.736338,4.661397,3.754825,14.0,0.376,NaN,14.057,22.353
614,Afghanistan,AFG,2004,46.330,221.830531,11862726,11690825,23553551,10.163449,8.152273,6.913806,5.733671,4.668712,3.760830,14.0,0.392,NaN,14.225,22.500
771,Afghanistan,AFG,2005,45.263,254.115274,12302104,12109086,24411191,10.306492,8.193682,6.942262,5.773830,4.700669,3.779947,14.2,0.400,46.151929,14.361,22.703
932,Afghanistan,AFG,2006,44.721,274.015394,12828447,12614497,25442944,10.440091,8.283211,6.980595,5.822531,4.739884,3.804654,14.3,0.409,NaN,14.196,22.907
1093,Afghanistan,AFG,2007,43.858,376.318296,13067961,12835340,25903301,10.545514,8.130697,6.741275,5.690068,4.681711,3.788131,14.1,0.424,NaN,14.019,23.113
1255,Afghanistan,AFG,2008,41.506,382.533804,13339006,13088192,26427199,10.728407,8.078060,6.542683,5.575155,4.633562,3.778257,14.0,0.430,NaN,13.900,23.320
1417,Afghanistan,AFG,2009,41.157,453.387382,13827977,13557331,27385307,10.977065,8.275737,6.559400,5.585952,4.655931,3.801099,14.3,0.440,NaN,13.816,23.528
1579,Afghanistan,AFG,2010,40.602,562.499219,14240377,13949295,28189672,11.205226,8.412052,6.524240,5.542244,4.650074,3.811522,14.4,0.448,51.821789,13.826,23.737
1743,Afghanistan,AFG,2011,39.855,608.738856,14780282,14468875,29249157,11.420183,8.660642,6.631597,5.562094,4.677033,3.837513,14.7,0.456,56.247228,14.134,23.948
1908,Afghanistan,AFG,2012,40.009,653.417479,15399105,15067373,30466479,11.577440,8.954238,6.822633,5.612657,4.719973,3.870701,15.0,0.466,54.700233,14.484,24.160
2073,Afghanistan,AFG,2013,39.601,638.733185,15946572,15594637,31541209,11.663077,9.170236,6.967998,5.618983,4.735564,3.892319,15.2,0.474,58.791659,15.339,24.373
2238,Afghanistan,AFG,2014,39.105,626.512930,16543889,16172321,32716210,11.704059,9.405484,7.162352,5.654473,4.758145,3.919042,15.5,0.479,61.865329,16.224,24.587
2403,Afghanistan,AFG,2015,38.803,566.881133,17071446,16682054,33753499,11.704731,9.568732,7.310218,5.673438,4.758590,3.937261,15.7,0.478,60.597015,16.893,24.803
2568,Afghanistan,AFG,2016,37.936,523.053012,17520861,17115346,34636207,11.691610,9.657797,7.407560,5.685865,4.735805,3.944881,15.8,0.481,57.203704,17.567,25.020
2733,Afghanistan,AFG,2017,37.342,526.140801,18028696,17614722,35643418,11.684561,9.758068,7.551135,5.754476,4.723907,3.956347,16.0,0.482,53.355363,18.251,25.250
2898,Afghanistan,AFG,2018,36.927,492.090632,18549862,18136922,36686784,11.671460,9.832507,7.706338,5.851933,4.715853,3.965902,16.1,0.483,52.804620,18.577,25.495
3064,Afghanistan,AFG,2019,36.466,497.741429,19090409,18679089,37769499,11.642337,9.885725,7.868727,5.973434,4.718040,3.973084,16.3,0.488,52.417041,18.898,25.754
3230,Afghanistan,AFG,2020,36.051,512.055098,19692301,19279930,38972230,11.593395,9.949606,8.056326,6.128982,4.751594,3.983536,16.6,0.483,NaN,13.700,26.026
3396,Afghanistan,AFG,2021,35.842,355.777826,20254878,19844584,40099462,11.537062,9.976438,8.203374,6.275088,4.804883,3.988522,16.7,0.478,NaN,NaN,26.314

# Remplacement des valeurs manquantes pour Sao Tome et Principe pour 2000

In [43]:
df_GDP_cleaning.loc[(df_GDP_cleaning['Country Name'] == 'Sao Tome and Principe') & (df_GDP_cleaning['Year'] == 2000), 'GDP per Capita'] = 557

In [44]:
df_GDP_cleaning.loc[df_GDP_cleaning["Country Name"]=="Sao Tome and Principe"]

,Country Name,Country Code,Year,Birth Rate,GDP per Capita,Population_male,Population_female,Population_total,15_to_19_women_rate,20_to_24_women_rate,25_to_29_women_rate,30_to_34_women_rate,35_to_39_women_rate,40_to_44_women_rate,Median_age,Human Development Index,PM2.5_pollution,Female_employment_rate,Urban population rate
129,Sao Tome and Principe,STP,2000,39.438,557.000000,71620,72094,143714,12.508669,9.833689,7.089356,5.825728,5.106528,3.981607,16.7,0.501,34.152030,30.797,53.424
281,Sao Tome and Principe,STP,2001,39.941,519.295583,72901,73356,146258,12.420849,10.166107,7.233851,5.762952,5.073852,4.108020,16.9,0.507,NaN,27.756,54.377
435,Sao Tome and Principe,STP,2002,39.850,568.409673,74706,75135,149841,12.080841,10.382575,7.428579,5.771573,5.002296,4.217048,17.0,0.511,NaN,27.600,55.555
591,Sao Tome and Principe,STP,2003,39.633,663.920664,76681,77081,153762,11.693619,10.496818,7.681580,5.817944,4.939641,4.298753,17.2,0.519,NaN,27.625,56.766
747,Sao Tome and Principe,STP,2004,39.396,726.597741,78656,79040,157697,11.346715,10.499681,7.942764,5.887488,4.898122,4.339547,17.3,0.525,NaN,28.306,57.972
906,Sao Tome and Principe,STP,2005,39.075,843.955111,80650,81031,161680,11.061884,10.396085,8.173466,5.992805,4.887666,4.334170,17.4,0.531,34.468432,27.744,59.165
1067,Sao Tome and Principe,STP,2006,38.672,861.518202,82666,83058,165725,10.836940,10.200642,8.350741,6.140853,4.910394,4.286738,17.5,0.542,NaN,27.782,60.348
1229,Sao Tome and Principe,STP,2007,38.241,878.135470,84721,85124,169845,10.655632,9.941967,8.475283,6.313731,4.952775,4.221489,17.6,0.545,NaN,28.059,61.520
1391,Sao Tome and Principe,STP,2008,37.810,1080.556568,86800,87204,174004,10.497858,9.671630,8.542088,6.494579,5.004386,4.167837,17.6,0.546,NaN,28.531,62.680
1553,Sao Tome and Principe,STP,2009,37.336,1126.538585,88860,89268,178128,10.363736,9.433952,8.545055,6.665322,5.064525,4.143142,17.7,0.552,NaN,28.801,63.823
1717,Sao Tome and Principe,STP,2010,36.873,1043.281427,90858,91281,182138,10.273826,9.247868,8.491956,6.801562,5.148964,4.161897,17.7,0.554,30.471586,29.241,64.952
1882,Sao Tome and Principe,STP,2011,36.628,1217.212064,92829,93216,186044,10.234295,9.122361,8.389654,6.893666,5.272700,4.219233,17.8,0.556,32.120563,29.556,66.064
2047,Sao Tome and Principe,STP,2012,36.148,1207.700702,94793,95131,189924,10.168084,8.961853,8.191336,6.969337,5.417792,4.278311,17.8,0.562,29.383295,29.875,67.160
2212,Sao Tome and Principe,STP,2013,35.159,1378.230193,96719,97038,193757,10.088779,8.745498,7.914900,7.032260,5.566863,4.326118,17.7,0.573,30.767977,29.884,68.208
2377,Sao Tome and Principe,STP,2014,34.032,1484.170105,98594,98903,197497,10.075529,8.554341,7.640820,7.053376,5.713174,4.380049,17.7,0.584,28.006756,29.911,69.213
2542,Sao Tome and Principe,STP,2015,32.754,1292.733055,100410,100713,201124,10.129724,8.400562,7.391760,7.016438,5.845294,4.457694,17.7,0.596,36.144807,29.897,70.174
2707,Sao Tome and Principe,STP,2016,31.602,1428.257908,102168,102465,204632,10.262529,8.285268,7.181477,6.912604,5.957644,4.575709,17.8,0.603,34.730528,29.949,71.092
2872,Sao Tome and Principe,STP,2017,30.410,1547.822710,103865,104172,208036,10.462504,8.212860,7.011961,6.741255,6.060650,4.725838,17.8,0.612,29.995407,30.014,71.968
3038,Sao Tome and Principe,STP,2018,29.535,1815.605495,105507,105837,211344,10.691913,8.195622,6.868109,6.532215,6.149078,4.885815,17.9,0.617,31.121630,30.087,72.803
3204,Sao Tome and Principe,STP,2019,28.917,1924.408150,107123,107476,214599,10.926160,8.239049,6.747553,6.324668,6.198128,5.041125,18.0,0.622,31.058858,30.170,73.598
3370,Sao Tome and Principe,STP,2020,28.435,2155.265868,109112,109528,218641,11.175630,8.411966,6.721538,6.150454,6.180127,5.173083,18.2,0.619,NaN,29.256,74.354
3536,Sao Tome and Principe,STP,2021,28.263,2350.452701,111305,111802,223107,11.399170,8.680524,6.760613,6.025384,6.092467,5.278081,18.4,0.618,NaN,29.381,75.073